pub enum Tile {
    // Bamboos
    Souzu1 = 1,
    Souzu2 = 2,
    Souzu3 = 3,
    Souzu4 = 4,
    Souzu5 = 5,
    Souzu6 = 6,
    Souzu7 = 7,
    Souzu8 = 8,
    Souzu9 = 9,
    // Circles
    Pinzu1 = 11,
    Pinzu2 = 12,
    Pinzu3 = 13,
    Pinzu4 = 14,
    Pinzu5 = 15,
    Pinzu6 = 16,
    Pinzu7 = 17,
    Pinzu8 = 18,
    Pinzu9 = 19,
    // Characters
    Manzu1 = 21,
    Manzu2 = 22,
    Manzu3 = 23,
    Manzu4 = 24,
    Manzu5 = 25,
    Manzu6 = 26,
    Manzu7 = 27,
    Manzu8 = 28,
    Manzu9 = 29,
    // Dragons
    Red = 31,
    White = 32,
    Green = 33,
    // Winds
    East = 34,
    West = 35,
    North = 36,
    South = 37,
}

impl Tile {
    pub fn from(value: i32) -> Option<Self> {
        match value {
            1 => Some(Tile::Souzu1),
            2 => Some(Tile::Souzu2),
            3 => Some(Tile::Souzu3),
            4 => Some(Tile::Souzu4),
            5 => Some(Tile::Souzu5),
            6 => Some(Tile::Souzu6),
            7 => Some(Tile::Souzu7),
            8 => Some(Tile::Souzu8),
            9 => Some(Tile::Souzu9),
            11 => Some(Tile::Pinzu1),
            12 => Some(Tile::Pinzu2),
            13 => Some(Tile::Pinzu3),
            14 => Some(Tile::Pinzu4),
            15 => Some(Tile::Pinzu5),
            16 => Some(Tile::Pinzu6),
            17 => Some(Tile::Pinzu7),
            18 => Some(Tile::Pinzu8),
            19 => Some(Tile::Pinzu9),
            21 => Some(Tile::Manzu1),
            22 => Some(Tile::Manzu2),
            23 => Some(Tile::Manzu3),
            24 => Some(Tile::Manzu4),
            25 => Some(Tile::Manzu5),
            26 => Some(Tile::Manzu6),
            27 => Some(Tile::Manzu7),
            28 => Some(Tile::Manzu8),
            29 => Some(Tile::Manzu9),
            31 => Some(Tile::Red),
            32 => Some(Tile::White),
            33 => Some(Tile::Green),
            34 => Some(Tile::East),
            35 => Some(Tile::West),
            36 => Some(Tile::North),
            37 => Some(Tile::South),
            _ => None,
        }
    }
}